name: Test

on:
  workflow_dispatch:

jobs:
  run:
    strategy:
      matrix:
        node: ['20', '22.5.1']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: npm ci
        run: npm ci
      # - name: run lint
      #   run: npm run lint
      - name: install Playwright
        run: npx playwright install --with-deps > /dev/null
      - name: run features
        run: npm run test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-result-report-${{ matrix.node }}
          path: reports/report.html
